{% set name = "eth-typing" %}
{% set version = "5.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eth_typing-{{ version }}.tar.gz
  sha256: 83debf88c9df286db43bb7374974681ebcc9f048fac81be2548dbc549a3203c0

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python
    - typing_extensions >=4.5

test:
  source_files:
    - tests
  imports:
    - eth_typing
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ethereum/eth-typing
  summary: 'eth-typing: Common type annotations for ethereum python packages'
  description: 'eth-typing: Common type annotations for ethereum python packages'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://eth-typing.readthedocs.io/en/stable/
  dev_url: https://github.com/ethereum/eth-typing

extra:
  recipe-maintainers:
    - step21
