{% set name = "eth-typing" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 079e4c41e98cf2635d3830a99f3cbd7b1d73d2368464d4493c002bece545184a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<4.0
  run:
    - python >=3.5,<4.0

test:
  imports:
    - eth_typing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-typing
  summary: 'eth-typing: Common type annotations for ethereum python packages'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
